import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Stitch Material Design palette
        primary: '#9e3d1d',
        'primary-container': '#be5433',
        'on-primary': '#ffffff',
        'primary-fixed': '#ffdbd0',
        'primary-fixed-dim': '#ffb59f',
        'on-primary-fixed': '#3a0a00',
        'on-primary-fixed-variant': '#812809',
        secondary: '#455f87',
        'secondary-container': '#b5d0fd',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#3e5980',
        'secondary-fixed': '#d5e3ff',
        'secondary-fixed-dim': '#adc8f5',
        'on-secondary-fixed': '#001c3b',
        'on-secondary-fixed-variant': '#2d486d',
        tertiary: '#79542b',
        'tertiary-container': '#956d40',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#fffbff',
        'tertiary-fixed': '#ffdcbc',
        'tertiary-fixed-dim': '#efbd8a',
        'on-tertiary-fixed': '#2c1700',
        'on-tertiary-fixed-variant': '#614018',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        surface: '#fff8f3',
        'surface-dim': '#e6d8c5',
        'surface-bright': '#fff8f3',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#fff2e2',
        'surface-container': '#fbecd9',
        'surface-container-high': '#f5e6d3',
        'surface-container-highest': '#efe0cd',
        'surface-variant': '#efe0cd',
        'on-surface': '#221a0f',
        'on-surface-variant': '#57423c',
        background: '#fff8f3',
        'on-background': '#221a0f',
        outline: '#8a726b',
        'outline-variant': '#ddc0b8',
        'inverse-surface': '#372f22',
        'inverse-on-surface': '#feefdb',
        'inverse-primary': '#ffb59f',
        'surface-tint': '#a13f1f',

        // Legacy colors (mapped to new palette for transition)
        sabbia: '#fff8f3',
        terracotta: {
          50: '#fffbff',
          100: '#fbe6e1',
          200: '#ffdbd0',
          300: '#ffb59f',
          400: '#be5433',
          500: '#9e3d1d',
          600: '#812809',
          700: '#3a0a00',
          800: '#3a0a00',
          900: '#3a0a00',
        },
        mare: {
          50: '#fff2e2',
          100: '#fbecd9',
          200: '#efe0cd',
          300: '#e6d8c5',
          400: '#57423c',
          500: '#455f87',
          600: '#3e5980',
          700: '#221a0f',
          800: '#221a0f',
          900: '#221a0f',
        },
        oro: '#79542b',
        crema: '#f5e6d3',
        notte: '#221a0f',
        salvia: {
          50: '#e8f9f5',
          100: '#c5f3e4',
          200: '#9aeac8',
          300: '#6adea9',
          400: '#3bd48d',
          500: '#13c892',
          600: '#0fa175',
          700: '#0b7c5a',
          800: '#085840',
          900: '#043628',
        },
      },
      fontFamily: {
        display: ['Playfair Display', 'Georgia', 'serif'],
        body: ['DM Sans', 'system-ui', '-apple-system', 'sans-serif'],
      },
      animation: {
        'fade-in': 'fadeIn 0.6s ease-out forwards',
        'slide-up': 'slideUp 0.6s ease-out forwards',
        'scale-in': 'scaleIn 0.4s ease-out forwards',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
      },
    },
  },
  plugins: [],
}

export default config
